site_name: Distributed Application Tools - Prescriptive Analytics

theme:
  name: material
    
repo_url: https://github.com/prescriptiveanalytics/spa-distributed-application-tools

markdown_extensions:
  - admonition
  - pymdownx.snippets
    
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://www.prescriptiveanalytics.at/
      name: Project Homepage

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          paths: [.]
          options:
            docstring_style: google
            show_submodules: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: false